name: Release Please

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v5
              id: release
              with:
                  release-type: node

            - name: Checkout code
              if: ${{ steps.release.outputs.release_created }}
              uses: actions/checkout@v4

            - name: Use Node.js
              if: ${{ steps.release.outputs.release_created }}
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm' # Optimize build runtime

            - name: Install dependencies
              if: ${{ steps.release.outputs.release_created }}
              run: npm ci

            - name: Build extension
              if: ${{ steps.release.outputs.release_created }}
              run: npm run compile

            - name: Publish extension
              if: ${{ steps.release.outputs.release_created }}
              run: npx @vscode/vsce publish --pat ${{ secrets.VSCE_PAT }}
